name: CI

on:
  push:
    branches:
    - master

jobs:
  build_cookbook_backend:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'cookbook-backend-api' }}
      run: |
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME --arg CONNECTION_STRING=${{ secrets.CONNECTION_STRING }} --arg DATABASE_NAME=${{ secrets.DATABASE_NAME }}
        heroku container:release web -a $APP_NAME